// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieReview.Models;

namespace MovieReview.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20200717110903_initialmigration1")]
    partial class initialmigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieReview.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LanguageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("movieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("movieId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("MovieReview.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MovieName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("reviewid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("reviewid");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieReview.Models.Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReviewName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MovieReview.Models.Language", b =>
                {
                    b.HasOne("MovieReview.Models.Movie", "movie")
                        .WithMany("languages")
                        .HasForeignKey("movieId");
                });

            modelBuilder.Entity("MovieReview.Models.Movie", b =>
                {
                    b.HasOne("MovieReview.Models.Review", "review")
                        .WithMany("movies")
                        .HasForeignKey("reviewid");
                });
#pragma warning restore 612, 618
        }
    }
}
